spring:
  datasource:
    url:
    username:
    password:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostreSQLDialect
  jpa:
    hibernate:
      ddl-auto: updated