spring:
  datasource:
    url: jdbc:postgresql://database:5432/database
    username: user
    password: password
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostreSQLDialect
  jpa:
    hibernate:
      ddl-auto: updated

  profiles:
    default: dev